name: ffi_sample
version: 0.0.1
description: >-
  使用ffi及ffigen的例子

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.7.0
  ffi: any

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ffigen: ^4.1.0

ffigen:
  output: 'bin/bindings.dart'
  headers:
    entry-points:
      - 'library/sample.h'